version: "3.8"

services:
  app:
    image: openjdk:17-jdk-slim
    container_name: java_app
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./app:/app # 애플리케이션 실행 파일 경로 (실행파일 위치 지정하기 편하게 명시)
      - app_logs:/app/logs # Java 로그 파일 경로
    working_dir: /app
    command: ["java", "-jar", "app.jar"]
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: Asia/Seoul # 한국 시간대 설정
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - pg_data:/var/lib/postgresql/data # 데이터베이스 데이터를 위한 볼륨
      - db_logs:/var/log/postgresql # DB 로그 파일을 위한 볼륨 마운트

volumes:
  pg_data:
  db_logs:
  app_logs:
